// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnikxnjcrywefklsumpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuaWt4bmpjcnl3ZWZrbHN1bXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTM4NDksImV4cCI6MjA2Nzc4OTg0OX0.Jr8tpyV2D722sgb4VsloONFTdmHhXtfuGHhI_qe4dc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});